openapi: 3.0.1
info:
  contact:
    name: Cloud Security Developer Community
  description: Manage the networks registered in your organization.
  title: Cisco Secure Access Networks API
  version: 2.0.0
servers:
- url: "https://api.sse.cisco.com/{basePath}"
  variables:
    basePath:
      default: deployments/v2
security:
- oauthFlow: []
tags:
- name: Networks
- name: Secure Access
paths:
  /networks:
    get:
      description: List the Networks in the organization.
      operationId: listNetworks
      parameters:
      - description: The number of a page in the collection.
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          format: int32
          minimum: 1
          type: integer
        style: form
      - description: The number of records to return from the collection on the page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 100
          format: int32
          maximum: 100
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - originId: 1234
                name: network name
                ipAddress: network ip address
                prefixLength: 32
                isDynamic: true
                isVerified: true
                status: OPEN
                createdAt: 2020-03-09T22:18:26.625Z
              schema:
                items:
                  $ref: "#/components/schemas/NetworkObject"
                type: array
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_400_response"
          description: Bad Request
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_401_response"
          description: Unauthorized
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_403_response"
          description: Forbidden
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_404_response"
          description: Not Found
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_500_response"
          description: Internal Server Error
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
      security:
      - oauthFlow:
        - deployments.networks:read
      summary: List Networks
      tags:
      - Networks
    post:
      description: "Create a network. Before you can create a network, contact Support\
        \ to get your IP range verified."
      operationId: createNetwork
      requestBody:
        content:
          application/json:
            example:
              name: network name
              prefixLength: 32
              isDynamic: true
              status: OPEN
            schema:
              $ref: "#/components/schemas/createNetwork_request"
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                originId: 1234
                name: name of the network
                ipAddress: network ip address
                prefixLength: 32
                isDynamic: true
                isVerified: true
                status: OPEN
                createdAt: 2020-03-09T22:18:26.625Z
              schema:
                $ref: "#/components/schemas/NetworkObject"
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_400_response"
          description: Bad Request
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_401_response"
          description: Unauthorized
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createNetwork_403_response"
          description: Forbidden
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_404_response"
          description: Not Found
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_500_response"
          description: Internal Server Error
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Create Network
      tags:
      - Networks
  /networks/{networkId}:
    delete:
      description: Delete a network registered in the organization.
      operationId: deleteNetwork
      parameters:
      - description: The ID of the network.
        example: 13456
        explode: false
        in: path
        name: networkId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "204":
          content:
            application/json:
              schema:
                nullable: true
                type: string
              example: null
          description: No Content
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_400_response"
          description: Bad Request
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_401_response"
          description: Unauthorized
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_403_response"
          description: Forbidden
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_404_response"
          description: Not Found
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_500_response"
          description: Internal Server Error
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Delete Network
      tags:
      - Networks
    get:
      description: Get a Network registered in the organization.
      operationId: getNetwork
      parameters:
      - description: The ID of the network.
        example: 13456
        explode: false
        in: path
        name: networkId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                originId: 1234
                name: network name
                ipAddress: network ip address
                prefixLength: 32
                isDynamic: true
                isVerified: true
                status: OPEN
                createdAt: 2020-03-09T22:18:26.625Z
              schema:
                $ref: "#/components/schemas/NetworkObject"
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_400_response"
          description: Bad Request
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_401_response"
          description: Unauthorized
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_403_response"
          description: Forbidden
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_404_response"
          description: Not Found
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_500_response"
          description: Internal Server Error
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
      security:
      - oauthFlow:
        - deployments.networks:read
      summary: Get Network
      tags:
      - Networks
    put:
      description: "Update a Network. Before you can update the network's IP address,\
        \ contact Support to get your IP range verified."
      operationId: updateNetwork
      parameters:
      - description: The ID of the network.
        example: 13456
        explode: false
        in: path
        name: networkId
        required: true
        schema:
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            example:
              name: network name
              isDynamic: true
              status: OPEN
            schema:
              $ref: "#/components/schemas/updateNetwork_request"
        description: Update a network.
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                originId: 1234
                name: network name
                ipAddress: network ip address
                prefixLength: 32
                isDynamic: true
                isVerified: true
                status: OPEN
                createdAt: 2020-03-09T22:18:26.625Z
              schema:
                $ref: "#/components/schemas/NetworkObject"
          description: OK
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_400_response"
          description: Bad Request
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_401_response"
          description: Unauthorized
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/updateNetwork_403_response"
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_404_response"
          description: Not Found
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listNetworks_500_response"
          description: Internal Server Error
          headers:
            Content-Type:
              $ref: "#/components/headers/Content-Type"
            Date:
              $ref: "#/components/headers/Date"
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Update Network
      tags:
      - Networks
components:
  headers:
    Content-Type:
      description: The MIME content type of the response body.
      example: application/json
      explode: false
      schema:
        type: string
      style: simple
    Date:
      description: The timestamp of the response.
      example: 2023-03-14T18:34:25Z
      explode: false
      schema:
        pattern: "^[0-90-90-90-9-0-90-9-0-90-9T0-90-9:0-90-9:0-90-9Z]+$"
        type: string
      style: simple
  parameters:
    paginationPageParam:
      description: The number of a page in the collection.
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: 1
        format: int32
        minimum: 1
        type: integer
      style: form
    paginationLimitParam:
      description: The number of records to return from the collection on the page.
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 100
        format: int32
        maximum: 100
        minimum: 1
        type: integer
      style: form
    networkId:
      description: The ID of the network.
      example: 13456
      explode: false
      in: path
      name: networkId
      required: true
      schema:
        type: integer
      style: simple
  responses:
    "400Error":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/listNetworks_400_response"
      description: Bad Request
      headers:
        Content-Type:
          $ref: "#/components/headers/Content-Type"
        Date:
          $ref: "#/components/headers/Date"
    "401Error":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/listNetworks_401_response"
      description: Unauthorized
      headers:
        Content-Type:
          $ref: "#/components/headers/Content-Type"
        Date:
          $ref: "#/components/headers/Date"
    "403Error":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/listNetworks_403_response"
      description: Forbidden
      headers:
        Content-Type:
          $ref: "#/components/headers/Content-Type"
        Date:
          $ref: "#/components/headers/Date"
    "404Error":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/listNetworks_404_response"
      description: Not Found
      headers:
        Content-Type:
          $ref: "#/components/headers/Content-Type"
        Date:
          $ref: "#/components/headers/Date"
    "500Error":
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/listNetworks_500_response"
      description: Internal Server Error
      headers:
        Content-Type:
          $ref: "#/components/headers/Content-Type"
        Date:
          $ref: "#/components/headers/Date"
  schemas:
    prefixLength:
      description: The length of the prefix. Set a prefix length that is greater than
        28 and less than 33.
      example: 30
      maximum: 32
      minimum: 29
      type: integer
    NetworkObject:
      description: The properties of the Network resource.
      example:
        originId: 1234
        name: name of the network
        ipAddress: The network IP address
        prefixLength: 32
        isDynamic: true
        isVerified: true
        status: OPEN
        createdAt: 2020-03-09T22:18:26.625Z
      properties:
        originId:
          description: The origin ID.
          type: integer
        name:
          description: The name of the network.
          type: string
        ipAddress:
          description: The IP address of the network.
          type: string
        prefixLength:
          description: The length of the prefix. Set a prefix length that is greater
            than 28 and less than 33.
          example: 30
          maximum: 32
          minimum: 29
          type: integer
        isDynamic:
          description: Specifies whether the network has a dynamic IP.
          type: boolean
        isVerified:
          description: Specifies whether the network is verified.
          type: boolean
        status:
          description: The status of the network.
          pattern: ^(OPEN|CLOSED)$
          type: string
        createdAt:
          description: The date and time (timestamp) when the network was created.
          example: 2018-06-13T16:07:07.222Z
          format: date-time
          type: string
      required:
      - createdAt
      - ipAddress
      - isDynamic
      - isVerified
      - name
      - originId
      - prefixLength
      - status
      type: object
    listNetworks_400_response:
      example:
        error: Validation Error
        message: message
        statusCode: 400
      properties:
        statusCode:
          description: HTTP status code
          example: 400
          type: integer
        error:
          description: A brief description of the error
          example: Validation Error
          type: string
        message:
          description: Detailed error message
          type: string
      type: object
    listNetworks_401_response:
      example:
        error: Validation error
        message: message
        statusCode: 401
      properties:
        statusCode:
          description: HTTP status code
          example: 401
          type: integer
        error:
          description: A brief description of the error
          example: Validation error
          type: string
        message:
          description: Detailed error message
          type: string
      type: object
    listNetworks_403_response:
      example:
        error: Forbidden
        message: message
        statusCode: 403
      properties:
        statusCode:
          description: HTTP status code
          example: 403
          type: integer
        error:
          description: A brief description of the error
          example: Forbidden
          type: string
        message:
          description: Detailed error message
          type: string
      type: object
    listNetworks_404_response:
      example:
        error: Not Found
        message: message
        statusCode: 404
      properties:
        statusCode:
          description: HTTP status code
          example: 404
          type: integer
        error:
          description: A brief description of the error
          example: Not Found
          type: string
        message:
          description: Detailed error message
          type: string
      type: object
    listNetworks_500_response:
      example:
        error: Internal error
        message: message
        statusCode: 500
      properties:
        statusCode:
          description: HTTP status code
          example: 500
          type: integer
        error:
          description: A brief description of the error
          example: Internal error
          type: string
        message:
          description: Detailed error message
          type: string
      type: object
    createNetwork_request:
      properties:
        name:
          description: The name of the network.
          maxLength: 50
          minLength: 1
          type: string
        ipAddress:
          description: The IP address of the network.
          type: string
        prefixLength:
          description: The length of the prefix. Set a prefix length that is greater
            than 28 and less than 33.
          example: 30
          maximum: 32
          minimum: 29
          type: integer
        isDynamic:
          description: Specifies whether the IP is dynamic.
          type: boolean
        status:
          description: The status of the network.
          pattern: ^(OPEN|CLOSED)$
          type: string
      required:
      - isDynamic
      - name
      - prefixLength
      - status
      type: object
    createNetwork_403_response:
      example:
        error: Forbidden
        message: The IP address that you provided is outside of your verified CIDR
          blocks.
        statusCode: 403
      properties:
        statusCode:
          description: HTTP status code
          example: 403
          type: integer
        error:
          description: Shorthand error message
          example: Forbidden
          type: string
        message:
          description: Detailed error message
          example: The IP address that you provided is outside of your verified CIDR
            blocks.
          type: string
      type: object
    updateNetwork_request:
      properties:
        name:
          description: The name of the network.
          maxLength: 50
          minLength: 1
          type: string
        ipAddress:
          description: The IP address of the network.
          minLength: 7
          type: string
        prefixLength:
          description: The length of the prefix. Set a prefix length that is greater
            than 28 and less than 33.
          example: 30
          maximum: 32
          minimum: 29
          type: integer
        isDynamic:
          description: Specifies whether the IP address is dynamic.
          type: boolean
        status:
          description: The status of the network.
          pattern: ^(OPEN|CLOSED)$
          type: string
      required:
      - isDynamic
      - name
      - status
      type: object
    updateNetwork_403_response:
      example:
        error: Forbidden
        message: The IP address you provided is outside of your verified CIDR blocks
        statusCode: 403
      properties:
        statusCode:
          description: HTTP status code
          example: 403
          type: integer
        error:
          description: Shorthand error message
          example: Forbidden
          type: string
        message:
          description: Detailed error message
          example: The IP address you provided is outside of your verified CIDR blocks
          type: string
      type: object
  securitySchemes:
    oauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.networks:write: Write deployments networks
            deployments.networks:read: Read deployments networks
          tokenUrl: https://api.umbrella.com/auth/v2/token
      type: oauth2
